#!/usr/bin/python3

import subprocess
import sys

processes = []

statistics = sys.argv[1:]

for statistic in statistics:
    processes.append(
        subprocess.Popen(
            "./stats-%s" % (statistic),
            stdin=subprocess.PIPE,
            stdout=subprocess.PIPE))

for line in sys.stdin:
    # empty column = zero
    inputs = [x if x else "0" for x in line.strip().split('\t')]

    for x, process in zip(inputs, processes):
        process.stdin.write("{}\n".format(x).encode('utf-8'))

# inform the subprocess that is the end of input
[process.stdin.close() for process in processes]

# read the binary result, and decode
outputs = [process.stdout.read().decode('utf-8') for process in processes]
# format the ouput
outputs = [x.strip() for x in outputs]

print("\t".join(outputs), end="")
